[phases.setup]
nixPkgs = ["python39", "gcc", "postgresql"]

[phases.install]
cmds = ["cd backend && pip install -r requirements.txt"]

[phases.build]
cmds = ["cd backend && python manage.py collectstatic --noinput"]